version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      # Port 27017 di host (VPS) akan terhubung ke port 27017 di kontainer
      - "127.0.0.1:27017:27017" # <-- DIUBAH: Hanya bisa diakses dari dalam VPS itu sendiri
    volumes:
      - mongo-data:/data/db
    # --- BARU: Tambahkan environment untuk username dan password ---
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "07092004"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      mongodb:
        condition: service_healthy

  dashboard:
    build:
      context: .
      dockerfile: dashboard.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Dashboard is waiting for the bot to process data...' &&
        sleep 120 &&
        echo 'Starting Streamlit dashboard...' &&
        streamlit run dashboard.py
      "
    # Dashboard juga bergantung pada bot, secara tidak langsung juga pada mongodb
    depends_on:
      - bot

# --- BARU: Definisi Volume ---
volumes:
  mongo-data: